### ISSUE TITLE
Air Pressure Ranges are not initialized/passed into the constructor

### ISSUE THREAD

**Issue by calvin-do** [ArcticWarriors/snobot2015#21]
https://github.com/ArcticWarriors/snobot2015/blob/master/snobot2015/src/com/snobot/claw/SnobotClaw.java#L32

**Comment by calvin-do** [comment]
Split initialization into two lines and then initialize the values in the constructor. (Read the values from the preferences?)

**Comment by ag-ayush** [comment]
Does mRobotAirPressure need to be passed in the constructor?
