### ISSUE TITLE
Remove the button selection sendable chooser / Add drive mode

### ISSUE THREAD

**Issue by team174-calabria** [ArcticWarriors/snobot2015#31]
https://github.com/ArcticWarriors/snobot2015/blob/master/snobot2015/src/com/snobot/Snobot.java#L118

**Comment by ag-ayush** [comment]
So far I have removed the button selection sendable chooser completely, but I replaced the buttons with A for tank and B for Arcade, therefore those need to send through preferences instead. Also, I do need to add drive mode chooser. This a reminder for me.
