### ISSUE TITLE
Ensure that gyro value is within the range 0 to 360

### ISSUE THREAD

**Issue by alecHussak** [ArcticWarriors/snobot2015#41]
Need to add while-loops to calculateDirection() in case gyroDegrees exceeds 720 degrees.
Link: https://github.com/ArcticWarriors/snobot2015/blob/master/snobot2015/src/com/snobot/position/SnobotPosition.java#L105

**Comment by calvin-do** [comment]
Could use while loop or maybe even modulo operator...

**Comment by alecHussak** [comment]
Well that was about the easiest fix ever.
