### ISSUE TITLE
SnobotClaw: Air Pressure names, Preferences

### ISSUE THREAD

**Issue by team174-calabria** [ArcticWarriors/snobot2015#53]
https://github.com/ArcticWarriors/snobot2015/blob/master/snobot2015/src/com/snobot/claw/SnobotClaw.java#L22

Air pressure A/B not descriptive.  
Preferences doesn't get max.  
Remove todo's if done.  Remove extra lines/spacing issues.

**Comment by ag-ayush** [comment]
I believe this issue has been fixed by making the air pressure A/B to RobotPressure.
