### ISSUE TITLE
Positioner is-a subsystem?

### ISSUE THREAD

**Issue by pjreiniger** [ArcticWarriors/snobot2015#62]
the positioner seems to have a lot of the functions common to a subystem... update, update SD, update logger.  Should it be a subsystem?

https://github.com/ArcticWarriors/snobot2015/blob/master/snobot2015/src/com/snobot/Snobot.java#L219

**Comment by alecHussak** [comment]
Not sure what to do for rereadPreferences(), stop(), or control(). Otherwise we are good to go.
