### ISSUE TITLE
SnobotFlightJoystick: Get values in Update

### ISSUE THREAD

**Issue by team174-calabria** [ArcticWarriors/snobot2015#68]
https://github.com/ArcticWarriors/snobot2015/blob/master/snobot2015/src/com/snobot/joystick/SnobotFlightstickJoystick.java#L111

Update - get the values.
Control - use values
getValue - returns the values gotten in the update.

**Comment by ag-ayush** [comment]
I believe that both joysticks now get the value in update and return them through member variable.
